import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.5
blur = true
# decorations = "Buttonless"

[window.padding]
x = 10
y = 10


[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"

