#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_tempalate = '{{ .UserName }}@{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = 'p:os'
    template = '{{ .Icon }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:pink'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = ' ~'
      style = 'agnoster_full'
      # max_depth = 4
      # style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:lavender'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      # commit_icon = ' '
      commit_icon = '@ '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'p:base'
    background = 'p:text'
    template = ' {{ .CurrentDate | date .Format }}  '

    [blocks.segments.properties]
      time_format = 'Jan 2 15:04:05'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[palette]
  blue = '#89B4FA'
  lavender = '#B4BEFE'
  pink = '#F5C2E7'
  yellow = '#F9E2AF'
  red = '#F38BA8'
  green = '#A6E3A1'
  text = '#CDD6F4'
  base = '#1E1E2E'
  closer = 'p:os'
  os = '#ACB0BE'
